### ISSUE TITLE
need to add a list of suspicious programs

### ISSUE THREAD

**Issue by Midoruya** [Midoruya/rust-cheat-checker#17]

**Comment by EfendicKemal** [comment]
ProcessHacker , ExtremeInjector and other Injectors

**Comment by Midoruya** [comment]
> ProcessHacker , ExtremeInjector and other Injectors

Ok I add this

**Comment by Midoruya** [comment]
![image](https://user-images.githubusercontent.com/51470828/210520912-2e40df79-3ac1-429f-be46-74976a895f15.png)
