### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by EfendicKemal** [Midoruya/rust-cheat-checker#19]
High Cpu Usage and Ram Usage.

Also the Icons are missing for me :/

**Comment by Midoruya** [comment]
Because at the moment when the applications are launched, it starts analyzing all the files on the PC

**Comment by Midoruya** [comment]
> High Cpu Usage and Ram Usage.
> 
> Also the Icons are missing for me :/

and you can tell me in when moment this happens

**Comment by Midoruya** [comment]
I fix this. 
But when your start up system scaning will be high cpu usage
